language: cpp
os: linux
dist: xenial
compiler: gcc

addons:
    sonarcloud:
        organization: "osrep"
        token:
            secure:"A1QG/p8l4b39Udsap2BO8WuYgUrZP2fsDkfnradMI9XJnzQac1W10SA6M70bx54+18D8mJ7mY/EG/5B1PqCpbnY8PfyJ5PrQACptFwpgqogq9S75Uz7KXGTPBuMy4VBNrdfYCJHpmE4GKTiLsnI616SqFRfJUJqKshDjufFPzrIhYlkIW97g54AqBrBDAQ0Fh/Z+YCK2a+635b3NqyESPGakbv2WPz40bp+/sa3pIlEAXMvknA/ei1sc01XPPrWBHRTRQI2GHETPDfINiGAOCs/sUvslYSce/ZNFZVvhBcgb31RwZsaIJmUDTXzPYsQl+Hbc8ujwfLT+9r/IgbUgoz37FqSPSbkBaRTW32Gw8kSdC1JX2sRb8VbIYMZ1c7NcvbZRCr/5M9yExxvinbbshTg29KZQAUFuj7inaiQGpf4Uf7orenmIQOTJ901X1DLVxWnEWLMrLCaYozQjmHDq0cBZqXYIllFoHo7bmzGs1WlpEg0/kIpuciSfV+eud5kQd0pVfnEGxFyaQxVkG+TP21ThlghZJUJJp2q+5D9E16PHrfRq5iheNacGeOjVv3OWDYgMumNNIh+31slRqENWiWxsT8pWJiosyCkRT/XRWABoDWsxekZ25kbFlCHvQCnJgoUqCzwB9y1uvj17cgyuNK3W0hdps809/d5O2AvS8ME="

branches:
    only:
        - temp_travis
script:
    # Prepare the build system
    - mkdir build && cd build
    - cmake ..
    # Go back to the project root folder in order for Sonar to find its config file
    - cd ..
    # Wrap the compilation with the Sonar Build Wrapper
    - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
    # Run tests 
    # TODO use cmake --build build --target test ??
    - ./build/test/RuninTests
    # Run Sonar analysis
    - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

cache:

  directories:

    - '$HOME/.sonar/cache'
